# Librerías necesarias

In [3]:
import numpy as np
import random

# Codigo de la clase pricipal

In [1]:
import numpy as np
class ProblemaMochila:
    def __init__(self, ítems, utilidades, pesos, límite):
        self.ítems = ítems
        self.utilidades = np.array([list(utilidades.values())[i] for i in range(len(utilidades))])
        self.pesos = np.array([list(pesos.values())[i] for i in range(len(pesos))])
        self.límite = límite
        self.num_items = len(self.ítems)

    def vector_ítems(self, vector):
        return [self.ítems[i] for i in range(len(vector)) if vector[i] == 1]

    def generar_solucion_aleatoria(self):
        return np.array([random.randint(0, 1) for _ in range(self.num_items)])

    def mejor_cambio(self, indices, v_actual):
        i_best = indices[0]
        u_best = (self.utilidades[i_best]/self.pesos[i_best])*((-1)**(v_actual[i_best]))
        for i in indices:
            u_i = (self.utilidades[i]/self.pesos[i])*((-1)**(v_actual[i]))
            if u_i >= u_best:
                i_best = i
        return i_best

    def utilidad(self, vector):
        return self.utilidades.dot(vector)

    def num_solucion(self, vector):
        n_bin = ""
        for bin in vector:
            n_bin = n_bin + str(bin)
        return int(n_bin,2)

    def tabu_search(self, max_iter=20, L=8):
        tabu_list = [] # C
        c = 1
        X = self.generar_solucion_aleatoria()
        X_best = X.copy()
        Curl_W = X_best.dot(self.pesos)
        while c<=max_iter:
            N = {i for i in range(self.num_items)}
            if len(tabu_list) != 0:
                for i in tabu_list:
                    N.remove(i)
            aux = set()
            for i in N:
                if (X[i] == 0) and (Curl_W + self.pesos[i] > self.límite):
                    aux.add(i)
            N = N-aux
            if len(N) != 0:
                i_posible = self.mejor_cambio(list(N), X)
                if len(tabu_list) < L:
                    tabu_list.append(i_posible)
                else:
                    tabu_list.pop(0)
                    tabu_list.append(i_posible)
                X[i_posible] = 1-X[i_posible]
                if X[i_posible] == 1:
                    Curl_W = Curl_W + self.pesos[i_posible]
                else:
                    Curl_W = Curl_W - self.pesos[i_posible]
                if self.utilidad(X) > self.utilidad(X_best):
                    X_best = X.copy()
            c += 1
        return X_best, self.num_solucion(X_best), Curl_W, self.utilidad(X_best)

In [13]:
def run_tabu_search(problema, L,num_iteraciones):
  """
  Ejecuta la búsqueda tabú con los parámetros especificados.

  Args:
    problema: Instancia del problema del morral.
    L: Longitud de la lista de tabu.
    num_iteraciones: Número de iteraciones a ejecutar.

  Returns:
    Diccionario con los resultados de la búsqueda.
  """

  resultados = {}
  for i in range(num_iteraciones):
    solucion, num_solucion, Curl_W, utilidad = problema.tabu_search(L)
    resultados[i] = {
        "solucion": solucion.tolist(),
        "num_solucion": num_solucion,
        "Curl_W": Curl_W,
        "utilidad": utilidad,
    }
  return resultados



In [11]:
run_tabu_search(item_2 ,4 ,3)

AttributeError: 'list' object has no attribute 'tabu_search'

In [7]:
# Caso particular Problema de la Mochila
item = ["linterna", "libro", "baterías", "lata", "bolsa de dormir", "mapa", "celular", "encendedor", "asador", "computadora"]
utilidad = {"linterna":10, "libro":2, "baterías":4, "lata":7, "bolsa de dormir": 20, "mapa":6, "celular":7, "encendedor": 8, "asador":6, "computadora":7}
peso = {"linterna":3, "libro":5, "baterías":1, "lata":3, "bolsa de dormir": 8, "mapa":1, "celular": 2, "encendedor":1, "asador":10, "computadora":1}
lím = 10

Caso_1 = ProblemaMochila(ítems=item, utilidades=utilidad, pesos=peso, límite=lím)
item[2]

'baterías'

In [8]:
item_2 = ["linterna", "libro", "baterías", "lata", "bolsa de dormir"]
utilidad_2 = {"linterna":10, "libro":2, "baterías":4, "lata":7, "bolsa de dormir": 20}
peso_2 = {"linterna":3, "libro":5, "baterías":2, "lata":4, "bolsa de dormir": 8}
lím_2 = 9

Caso_2 = ProblemaMochila(ítems=item_2, utilidades=utilidad_2, pesos=peso_2, límite=lím_2)

In [12]:
item_libro = list(map(str, range(1, 25)))
utilidad_2 = {"1":10, "2":2, "baterías":4, "lata":7, "bolsa de dormir": 20}
peso_2 = {"linterna":3, "libro":5, "baterías":2, "lata":4, "bolsa de dormir": 8}
lím_2 = 9

# Pruebas de los atributos y funciones

In [ ]:
Caso_1.pesos, Caso_1.utilidades, Caso_1.num_items, Caso_1.límite

(array([ 3,  5,  1,  3,  8,  1,  2,  1, 10,  1]),
 array([10,  2,  4,  7, 20,  6,  7,  8,  6,  7]),
 10,
 10)

In [ ]:
Caso_1.generar_solucion_aleatoria()

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
Caso_1.vector_ítems([1, 1, 1, 0, 1, 1, 0, 1, 0, 0])

['linterna', 'libro', 'baterías', 'bolsa de dormir', 'mapa', 'encendedor']

In [ ]:
Caso_1.mejor_cambio([1,3,5,6,9],[1, 1, 1, 0, 1, 1, 0, 1, 0, 0])

9

In [ ]:
Caso_1.utilidad([1, 1, 1, 0, 1, 1, 0, 1, 0, 0])

50

In [ ]:
mejor_solucion_encontrada = Caso_1.tabu_search(20,8)
mejor_solucion_encontrada, Caso_1.vector_ítems(mejor_solucion_encontrada[0])

((array([1, 0, 1, 0, 0, 1, 1, 1, 0, 1]), 669, 5, 42),
 ['linterna', 'baterías', 'mapa', 'celular', 'encendedor', 'computadora'])

In [10]:
mejor_solucion_encontrada_2 = Caso_2.tabu_search(15,4)
mejor_solucion_encontrada_2, Caso_2.vector_ítems(mejor_solucion_encontrada_2[0])

((array([1, 0, 1, 1, 0]), 22, 9, 21), ['linterna', 'baterías', 'lata'])

# Pruebas Random

In [ ]:
N = {(1,2),(2,3),(2,5)}
N.add((1,2))
N.add((2,6))
N

{(1, 2), (2, 3), (2, 5), (2, 6)}

In [ ]:
a=int('01',2) # Imprime '0'
a

1